services:
  backend:
    build:
      context: ./backend
    container_name: rag-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data    # For embedding/index persistence

  frontend:
    build:
      context: ./frontend
    container_name: rag-frontend
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_HOST=backend
    depends_on:
      - backend
